config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    # comments routes
    resources :posts do
        resources :comments
    end

    root to: "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # private
  # def authenticate
  #     if !session[:is_signed_in]
  #         redirect_to "/signin"
  #     end
  # end

  # def current_user
  #   return user.find(sesion[:user_id])
  # end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show]

  # index
  def index
      @comments = Comment.all
  end

  #new
  def new
      @post = Post.find(params[:post_id])
      @comment = @post.comments.new

  end

  #create
  def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(comment_params)
      @comment.update({
          user_id: current_user.id
         })
      redirect_to post_path(@comment.post_id)
  end

  #show
  def show
      @post = Post.find(params[:post_id])
      @comment = Comment.find(params[:id])
      @user = current_user
  end

  #edit
  def edit
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @user = current_user
  end

  #update
  def update
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.update(comment_params)
      redirect_to post_path(@comment.post_id)
  end

  #destroy
  def destroy
      @comment = Comment.find(params[:id])
      @post = Post.find(params[:post_id])
      @comment.destroy
      redirect_to post_path(@post)
  end

  private
  def comment_params
      params.require(:comment).permit(:author, :comment_text, :post_date, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show]
  # index
  def index
    @posts = Post.all
  end

  #new
  def new
      @post = Post.new
  end

  #create
  def create
      @post = Post.create(post_params)
      #manually associate the current_user.id to the post
      @post.update({
          user_id: current_user.id
         })
      redirect_to post_path(@post)
  end

  #show
  def show
      @post = Post.find(params[:id])
      @user = current_user
      @comment = Comment.new
  end

  #edit
  def edit
      @post = Post.find(params[:id])

  end

  #update
  def update
      @post = Post.find(params[:id])
      #if current_user.id == @post.user_id
     @post.update(post_params)
     # end
      redirect_to post_path(@post)
  end

  #destroy
  def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
  end


  private
  def post_params
      params.require(:post).permit(:title, :author, :text, :post_date, :photo_url, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment_form.html.erb
<div >
<%= form_for [@post, @comment] do |f| %>
    <%= f.label :author %>
    <%= f.text_field :author %>

    <%= f.label :comment_text %>
    <%= f.text_area :comment_text %>

    <%= f.label :post_date %>
    <%= f.text_field :post_date %>

    <% # f.label :post_id %>
    <% # f.text_field :post_id %>

    <%= f.submit "Scribble Comment" %>

<% end %>
</div>

app/views/comments/edit.html.erb
<h2 class="comment-form">Update a comment</h2>

<%= render partial: "comment_form" %>


<%= form_for [@post, @comment], method: :delete do |f| %>
    <%= f.submit "Erase", class: "delete" %>
<% end %>

app/views/comments/new.html.erb
<h2 class="comment-form">Add a new comment</h2>

<%= render partial: "comment_form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
    <header class="logo">
        <%= link_to (image_tag("logo.png")), posts_path %>
    </header>

        <%= yield %>
    <footer>
        <nav>
            <ul>
                <li><%= link_to "Sign up", new_user_registration_path%></li>
                <li><%= link_to "Sign in", new_user_session_path%></li>
                <li><%= link_to "Sign out",   destroy_user_session_path, :method => :delete  %></li>
                <li>
                    <%= link_to "New Post", new_post_path %>

                </li>
            </ul>
        </nav>
        <p class="footer-text">Content copyright Scribble 2K15</p>
    </footer>
</body>
</html>

app/views/posts/_comment_form.html.erb
<div class="comment-form">


<%= form_for [@post, @comment] do |f| %>
    <%= f.label :author %>
    <%= f.text_field :author %>

    <%= f.label :comment_text %>
    <%= f.text_field :comment_text %>

    <%= f.label :post_date %>
    <%= f.text_field :post_date %>

    <%= f.label :post_id %>
    <%= f.text_field :post_id %>

    <%= f.submit "Scribble Comment" %>

<% end %>
</div>

app/views/posts/_form.html.erb
<%= form_for (@post) do |f| %>
<p>
    <%= f.label :title %>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :author %>
    <%= f.text_field :author %>
</p>
<p>
    <%= f.label :text %>
    <%= f.text_area :text %>
</p>
    <%= f.label :post_date %>
    <%= f.text_field :post_date %>
<p>
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
</p>
<p>
    <%= f.submit "Scribble" %>
</p>
<% end %>

app/views/posts/edit.html.erb
<h2>Update Post</h2>

<%= render partial: "form" %>

<%= form_for(@post, method: :delete) do |f| %>
    <% f.submit "Erase", class: "delete" %>
<% end %>

app/views/posts/index.html.erb
<div class="feed">
<% @posts.each do |post| %>
    <div class="post">
        <h3 class="headline"><%= link_to post.title, post_path(post) %></h3>
        <div class="blog-index">
            <h5>Scribbled by <%= post.author + " on " + post.post_date %></h5>
            <%= image_tag src="#{post.photo_url}", :class => "blog-photo" %>
            <p>
                <%= truncate(post.text, :length => 100) %>
                <%= link_to"(read more)", post_path(post) %>
            </p>
        </div>
        <p>
            Comments (<%= post.comments.count %>)
        </p>
    </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h2 class="comment-form">New Blog Post</h2>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<div class="show-container">
<h2 class="title"><%= @post.title %></h2>
<h4 class="blog-text">Scribbled by <%= @post.author + " on " + @post.post_date %>
<!-- if the user is the author of the post (based on user id), let him/her see the "(edit)" button -->
<% if @user %>
    <% if @post.user_id == @user.id %>
        <%= link_to " (Edit)", edit_post_path %>
        <% end %>
    <% end %>
</h4>
<%= image_tag src="#{@post.photo_url}", :class => "blog-photo" %>

<!-- <p class="full-text"> -->
<%= simple_format(@post.text, :class => "blog-text") %>
<!-- </p> -->

<h4>Comments </h4>
<% @post.comments.each do |comment| %>
    <div class="comment">
        <p>
            <%= comment.comment_text%>
        </p>
        <p class="comment-details">
            <%= comment.author + " on " + comment.post_date%>
                <!-- if the user is the author of the post (based on user id), let him/her see the "(edit)" button -->
                <% if @user %>
                    <% if comment.user_id == @user.id %>
                        <%= link_to "(edit)", edit_post_comment_path(@post, comment) %>
                    <% end %>
                <% end %>

        </p>
    </div>
<% end %>
<!-- If the user is logged in, prompt to sign in to comment. Otherwise, link to add a new comment -->

<% if @user == nil %>
    <h4><%= link_to "Sign in to comment", new_user_session_path %> </h4>
<% elsif %>
    <h4><%= link_to "Add a new comment", new_post_comment_path(@post)%> </h4>
<% end %>
</div>